name: Deploy to Prod on merge
'on':
  push:
    branches:
      - prod
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WATER_LEVEL_F93C4 }}'
          channelId: live
          target: prod
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
